frameworkVersion: '3'
useDotenv: true

service: serverless-authentication-app

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${env:NODE_ENV, 'development'}
  environment:
    user_pool_id: { Ref: UserPool }
    client_id: { Ref: UserClient }
    AWS_REGION: ${env:AWS_REGION}
    AWS_COGNITO_CLIENT_ID: ${env:AWS_COGNITO_CLIENT_ID}
    AWS_COGNITO_USER_POOL_ID: ${env:AWS_COGNITO_USER_POOL_ID}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
      Resource: "*"

functions:
  - ${file(./resources/functions.yml)}

resources:
  - ${file(./resources/cognito.yml)}